version: '3.1'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_sorage:/var/lib/mysql
     networks:
       mysql_internal:
     environment:
       MYSQL_ROOT_PASSWORD: passwordgoueshear
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wpuser
       MYSQL_PASSWORD: passwordgoueshear

   site:
     depends_on:
       - db
     image: wordpress
     networks:
       mysql_internal:
       wordpress_public:
     ports:
       - "80:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wpuser
       WORDPRESS_DB_PASSWORD: passwordgoueshear

volumes:
    db_sorage:
networks:
  mysql_internal:
    internal: true
  wordpress_public:
