version: '3.7'

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./joomla:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - joomla

  joomla:
    image: joomla:4.1.0-php7.4-fpm-alpine
    restart: always
    environment:
      - JOOMLA_DB_HOST=db
      - JOOMLA_DB_USER=postgres
      - JOOMLA_DB_PASSWORD=mysecretpassword
      - JOOMLA_DB_NAME=db
    volumes:
      - ./joomla:/var/www/html
      - ./makedb.php:/makedb.php
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./db:/var/lib/postgresql/data
